version: 2
updates:
  - package-ecosystem: npm
    directory: /ai-sdk-aipg
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /dify-aipg
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /langchain-aipg
    schedule:
      interval: weekly
